CXX = g++
CXXFLAGS = -Wall -std=gnu++0x

target: etapa1

etapa1: lex.yy.o main.o Symbols.o
	$(CXX) -o etapa1 lex.yy.o main.o Symbols.o

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $< -c

lex.yy.cpp: scanner.l
	flex scanner.l
	ren lex.yy.c lex.yy.cpp

clean:
	del etapa1.exe lex.yy.cpp *.o