CXX = g++
CXXFLAGS = -Wall -std=c++11
TARGET_NAME = etapa4

$(TARGET_NAME): y.tab.o lex.yy.o Symbols.o Semantic.o main.o Ast.o
	$(CXX) -o $(TARGET_NAME) y.tab.o lex.yy.o Semantic.o Symbols.o main.o

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $< -c

y.tab.o: y.tab.c
	$(CXX) -c y.tab.c

y.tab.c: parser.y
	yacc -d -v parser.y

lex.yy.o: lex.yy.c
	$(CXX) -c lex.yy.c

lex.yy.c: scanner.l
	flex --header-file=lex.yy.h scanner.l

clean:
	rm -f *.o $(TARGET_NAME) lex.yy.c lex.yy.h y.tab.c y.tab.h y.output